apiVersion: v1
kind: Service
metadata:
  name: schools-phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: phpmyadmin
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schools-phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        envFrom:
        - configMapRef:
            name: phpmyadmin-acceptance-config
        ports:
          - containerPort: 80
            name: phpmyadmin
        resources:
          requests:
            cpu: "10m"
            memory: "20Mi"
          limits:
            cpu: 20m
            memory: 35Mi

