version: '3'

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local

services:

  #Nginx Service
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    container_name: nginx
    ports:
      - "${DOCKER_WEBSERVER_HOST}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - phpfpm
      - mysqlschools
      - redis
    networks:
      - app-network

  #MySQL Service
  mysqlschools:
    image: mysql:5.7.34
    container_name: mysqlschools
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  #PHP Service
  phpfpm:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    container_name: phpfpm
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqlschools
      - redis
    ports:
      - "9000:9000"
    networks:
      - app-network

  #Composer Service
  composer:
    build:
      context: .
      dockerfile: ./docker/composer.dockerfile
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - phpfpm
    user: laravel
    networks:
      - app-network
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]

  #Artisan Service
  artisan:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    container_name: artisan
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqlschools
      - redis
    working_dir: /var/www/html
    user: laravel
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - app-network

  #PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - '${DOCKER_PHPMYADMIN_HOST}:80'
    environment:
      PMA_HOST: mysqlschools
      UPLOAD_LIMIT: 3000000000
    depends_on:
      - mysqlschools
    networks:
      - app-network

  #Redis Service
  redis:
    build:
      context: .
      dockerfile: ./docker/redis.dockerfile
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app-network
