apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOnsidXNlcm5hbWUiOiJyYWZhZWxwNzc3IiwicGFzc3dvcmQiOiJWaWRAbG9rYTQiLCJlbWFpbCI6InJhZmFlbHA3NzdAZ21haWwuY29tIiwiYXV0aCI6ImNtRm1ZV1ZzY0RjM056cFdhV1JBYkc5cllUUT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
