apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schools-pvc
spec:
  storageClassName: "schools-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: schools-sc
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-standard
  fstype: ext4
volumeBindingMode: WaitForFirstConsumer
