apiVersion: apps/v1
kind: Deployment
metadata:
  name: composer-php
  labels:
    app: composer
spec:
  replicas: 0
  selector:
    matchLabels:
      app: composer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: composer
    spec:
      containers:
        - image: rafaelp777/composer:1.0.1
          name: composer
          command: ["composer"]
          args: ["install"]
          resources:
            requests:
              cpu: "10m"
              memory: "20Mi"
            limits:
              cpu: 20m
              memory: 30Mi
          volumeMounts:
          - name: nginx-pv
            mountPath: /var/www/html
      restartPolicy: Always
      volumes:
      - name: nginx-pv
        persistentVolumeClaim:
          claimName: composer-pvc

