apiVersion: v1
kind: Service
metadata:
  name: schools-application
  labels:
    app: schools
spec:
  ports:
    - port: 8082
      targetPort: 80
  selector:
    app: schools
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schools-application
  labels:
    app: schools
spec:
  selector:
    matchLabels:
      app: schools
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: schools
    spec:
      containers:
      - image: rafaelp777/schools-masts:r01.0.2
        imagePullPolicy: Always
        name: schools
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: schoolsdb-secret
              key: password
        envFrom:
        - configMapRef:
            name: application-acceptance-config
        ports:
          - containerPort: 80
            name: schools
        resources:
          requests:
            cpu: 3m
            memory: 10Mi
          limits:
            cpu: 12m
            memory: 30Mi
      imagePullSecrets:
      - name: regcred
