apiVersion: v1
kind: Service
metadata:
  name: phpfpm
  labels:
    app: php
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: php

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - image: rafaelp777/phpfpm:r01.0.2
          name: php
          ports:
            - containerPort: 9000
              name: php
          resources:
            requests:
              cpu: 30m
              memory: 25Mi
            limits:
              cpu: 120m
              memory: 80Mi
